version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: fastapi-auth-mongo
    hostname: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./data:/data/db

  app:
    container_name: fastapi-auth-app
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    env_file: .env.develop
    volumes:
    - .:/fastapi-auth
    depends_on:
      - mongodb
    ports:
    - "8000:8000"